version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15
    container_name: stock-genie-postgres-dev
    environment:
      POSTGRES_DB: stockgenie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - stock-genie-dev-network
    restart: unless-stopped

  # Redis Cache for Development
  redis:
    image: redis:7-alpine
    container_name: stock-genie-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - stock-genie-dev-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: stock-genie-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_dev_data:/root/.ollama
    networks:
      - stock-genie-dev-network
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    deploy:
      resources:
        reservations:
          memory: 8G

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  ollama_dev_data:
    driver: local

networks:
  stock-genie-dev-network:
    driver: bridge
