# Stock Genie - LLM Configuration
llm:
  provider: ollama
  base-url: http://localhost:11434
  models:
    primary: mistral:7b
    backup: llama2:7b
    specialized:
      - mistral:7b  # Best for general stock analysis
      - llama2:7b   # Good for sentiment analysis
  settings:
    timeout: 30000
    max-tokens: 1000
    temperature: 0.7
    top-p: 0.9
  prompts:
    stock-analysis: |
      You are a financial analyst. Analyze the following stock data for {SYMBOL}:
      
      Price Data: {PRICE_DATA}
      Technical Indicators: {INDICATORS}
      
      Provide:
      1. Trend analysis
      2. Technical signal interpretation
      3. Risk assessment
      4. Buy/Sell/Hold recommendation with reasoning
      
      Keep response concise and actionable.
    
    sentiment-analysis: |
      As a specialized financial analyst, evaluate this stock data:
      
      {STOCK_DATA}
      
      Focus on:
      - Sentiment indicators
      - Market psychology
      - Risk factors
      - Investment recommendation
    
    technical-analysis: |
      Analyze the following technical indicators for {SYMBOL}:
      
      {INDICATORS}
      
      Provide:
      1. Signal interpretation
      2. Trend confirmation
      3. Entry/exit points
      4. Risk levels
    
    market-overview: |
      Provide a market overview based on:
      
      {MARKET_DATA}
      
      Include:
      1. Overall market sentiment
      2. Sector performance
      3. Key events
      4. Outlook
